[gcp_service_account]
type = "service_account"
project_id = "my-dash-velare"
private_key_id = "dd6ed538dc2f5aeeeec8f25d045b794469b2ea0c"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9Tbz77TYm/r21
y9uUBDUdEG+nRDZB494uTB3fLW1XFunivizwY7KMyw/00YhPKmr8JHKQBmZeJPRR
pknjnkwT6ymUAfgEazYmnxhT8Rfiu+5qz3nHOmHSNVWmaVWd7g9Y/P4RFfXio6IP
Q6RsKnCsy3Nhw1MFfWr+oOjLNX62qKC9A3uiyZx0qmEv3VxfGOk8qD0vbFjpSt32
0aSvYx9A0N+QEmwbDZNcrz3DC8P4anOyrGE9S701TZlnJtofZyBA4s5TT80fJqcC
gLrqDJj8DpF10Yt9/RjHYaxDC3SfHFKkugxJeaKrVtFcTq9CcX91AreVWaqPCmHG
5/g2LgHbAgMBAAECggEALxpPwtPEXLGYHMsryMm/OYskbRdQ9NYxK43vBOA1y6y8
55lwbyQvgk7omn8kjqY8Vp7vDp05DYXecQ6SZhu2TGKARv6yas8Oe0+s6v4bdmRS
r6sOXx9MxdRVioG9Nv3MPdU9lpzDQPB8W5X2LJ/mx2gcPqAuYThSzibVpfKao/Il
JOXVzsjuvPcA8Whh3CURZsDYeAbfVEn56D4N8QdCfiuTtQbxLjZXXjlDSvyj08t5
4jkUsn9qd4AT2AyoFXQ/azWESNmAony7z19yfmGm9xi+ibDYFzjSCyNYDnlzFh7h
HH923eROVMVCwhZid2KEPQLObaxxaMUB20tBP83t+QKBgQD4zZaFIaUDQ7oEiWH5
Ae+MFr+9UFxVjRftqhVv/0kB3ivLFA4I7KG2rj4/E6DcxZawSQ/0DvmOfg+p9ONC
9aUh/TrjHJ1pQwz5c2kleuqhyAzhg7AgYlr7fUgR5VQ2Dxz5WtjbzfJddkmMQ3Na
aM333LWO13Pg9D9bEcWLUqeofQKBgQDCx40SUB6n8xsAUcAlBAptvpc1LbVEwjx6
/rqB6K1geaR4PZ64B+NqMnFI98o+pk17I9ymxUteqULwFoc3/tEA1Orx4UBw074m
P98+LtgI3kOw0XCPMspUnNOVWGbTkPytJULUf29Hc3H4It7O0U2RrlN6lnLW+gfx
fmgileQ7NwKBgAxcanYCzefznXJMQQnWBsi2+J+3Nl8pu16bbKU70ay+FP7p6CiZ
WQ9yaLVJjFxrlKj9eEVv2QYzTSPsfr385k9h/WL7MPbh1esuyLKMAMw43Cr4F/AD
8vE7sDDza9OjvJTG5q9E9B2gmtbVIw4C1vjRhlOqcJ9kgyFLKL1bRekhAoGBAKgk
2dxoO76id7mz2NpbfaE1eZTXq3b68nj+8wR4V0tEVz3Re/XEIYaomvDxr66bo6Fc
2PtCsAi8t2NJH1uwZr6AD33VBOshbzHXy6EDkU0+ilLWyoNjxhR6+ZAgK0wSCn5x
/xowFGErAMTDXXJObtcHFVtrCyIX38mSZNUObmLLAoGAVfjStJ33aJXc8RE5klz9
PDVnQwfdLmC1xuDOdLjLc7slQyi9LHxMndEkXvzuUPp6s8uDyL4cImUPSEcYNDCl
o+6Q2kcfu8kjtkGyiEwo0SKgbag0kui5aOdOB2MuVwuSbRvmVCQmtD9Auu+5dnp2
PrNh/dwtbJjoJtscOYNa5ZU=
-----END PRIVATE KEY-----
"""
client_email = "streamlit-dashboard-velare@my-dash-velare.iam.gserviceaccount.com"
client_id = "111409552267201836478"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-dashboard-velare%40my-dash-velare.iam.gserviceaccount.com"
